AWSTemplateFormatVersion: 2010-09-09
Description: This template creates an EC2 instance based on the selection of an AMI ID.
Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.nano
      ImageId: ami-0c02fb55956c7d316
      KeyName: web1
  InstanceSecurityGroup:
      Type: 'AWS::EC2::SecurityGroup'
      Properties:
          GroupDescription: Allow ssh connect to host
          SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: '22'
            ToPort: '22'
            CidrIp: 0.0.0.0/0