AWSTemplateFormatVersion: 2010-09-09
Description: This template creates an EC2 instance based on the selection of an AMI ID.
Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
        InstanceType: t2.nano 
        ImageId: ami-0c02fb55956c7d316
        KeyName: web1
    Metadata:
      'AWS::CloudFormation::Init':
        configSets:
          InstallAndRun:
            - Install
            - Start
            - Enable
        Install:
          packages:
            yum:
              httpd: []
      UserData: !Base64 
        'Fn::Join':
          - ''
          - - |
              #!/bin/bash -xe
            - |
              yum update -y aws-cfn-bootstrap        
  InstanceSecurityGroup:
      Type: 'AWS::EC2::SecurityGroup'
      Properties:
          GroupDescription: Allow ssh and http connections to host
          SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: '22'
            ToPort: '22'
            CidrIp: 0.0.0.0/0
          - IpProtocol: tcp
            FromPort: '80'
            ToPort: '80'
            CidrIp: 0.0.0.0/0
