AWSTemplateFormatVersion: 2010-09-09
Description: This template creates an EC2 instance based on the selection of an AMI ID.
Resources:
  Web1:
    Type: 'AWS::EC2::Instance'
    Properties:
        InstanceType: t2.nano 
        ImageId: ami-0c02fb55956c7d316
        KeyName: web1
        UserData:
         'Fn::Base64': 
            !Sub |
              #!/bin/bash
              yum update -y
              yum install -y httpd.x86_64
              systemctl start httpd.service
              systemctl enable httpd.service
              echo ?Hello World from $(hostname -f)? > /var/www/html/index.html
  Web2:
    Type: 'AWS::EC2::Instance'
    Properties:
        InstanceType: t2.micro
        ImageId: ami-0c02fb55956c7d316
        KeyName: web1
        UserData:
         'Fn::Base64':  
            !Sub |
              #!/bin/bash
              yum update -y
              yum install -y httpd.x86_64
              systemctl start httpd.service
              systemctl enable httpd.service
              echo ?Hello World from $(hostname -f)? > /var/www/html/index.html
  InstanceSecurityGroup:
      Type: 'AWS::EC2::SecurityGroup'
      Properties:
          GroupDescription: Allow ssh connect to host
          SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: '22'
            ToPort: '22'
            CidrIp: 0.0.0.0/0
          - IpProtocol: tcp
            FromPort: '80'
            ToPort: '80'
            CidrIp: 0.0.0.0/0
        
             